version: 2
jobs:
  build:
    
    docker:
      - image: circleci/openjdk:8-jdk-browsers

    working_directory: ~/circleci/javatest1  
    steps:

      - checkout

      - restore_cache:
          key: javatest1-{{ checksum "pom.xml" }}
      
      - run: mvn dependency:go-offline
      
      - save_cache:
          paths:
            - ~/.m2
          key: javatest1-{{ checksum "pom.xml" }}
      
      - run: mvn package
      
      - store_test_results:
          path: target/surefire-reports
      
      - store_artifacts:
          path: target/javatest1-0.0.1-SNAPSHOT.jar
          
