version: 2
jobs:
  build:
    branches:
      only:
        - javatest1

    working_directory: ~/circlecitest

    docker:
      - image: circleci/openjdk:8-jdk-browsers

    steps:

      - checkout

      - restore_cache:
          key: circlecitest1-{{ checksum "pom.xml" }}
      
      - run: mvn dependency:go-offline
      
      - save_cache:
          paths:
            - ~/.m2
          key: circlecitest1-{{ checksum "pom.xml" }}
      
      - run: mvn package
      
      - store_test_results:
          path: target/surefire-reports
      
      - store_artifacts:
          path: target/javacirclecitest1-0.0.1-SNAPSHOT.jar
          
